spring.datasource.url=jdbc:postgresql://localhost:5432/medishield
spring.datasource.username=postgres
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Enable SQL script initialization for schema.sql and data.sql
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=false
